/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mediateur;

import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Fakhro
 */
public class GUI extends javax.swing.JFrame {

    DefaultTableModel tm;
    Vector<String> columnNames = new Vector<String>();
     
    Connecter maconnexion =new Connecter();
    Statement stmt;
    ResultSet r1;
    
    String requete="";
    String select ="";
    String from="";
    String where="";
    String agregat="";
    String groupby="";
    
    Integer cpt=0;
    
    
    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        
        la_requete.setEnabled(false);
        //table EMP
                
                
                CodeEmp.setSelected(false);
                NomEmp.setSelected(false);
                salaire.setSelected(false);
                NumDept.setSelected(false);
                Origine.setSelected(false);
                
                CodeEmp.setEnabled(false);
                NomEmp.setEnabled(false);
                salaire.setEnabled(false);
                NumDept.setEnabled(false);
                Origine.setEnabled(false);
                
                CodeEmp1.setSelectedIndex(0);
                NomEmp1.setSelectedIndex(0);
                salaire1.setSelectedIndex(0);
            //    salaire2.setSelectedIndex(0);
                NumDept1.setSelectedIndex(0);
                Origine1.setSelectedIndex(0);
                
                cond_agregat.setEnabled(false);
                CodeEmp1.setEnabled(false);
                NomEmp1.setEnabled(false);
                NumDept1.setEnabled(false);
                salaire1.setEnabled(false);
                salaire2.setEnabled(false);
                Origine1.setEnabled(false);
                
                CodeEmpT.setText("");
                NomEmpT.setText("");
                salaireT.setText("");
                NumDeptT.setText("");
                
                CodeEmpT.setEnabled(false);
                NomEmpT.setEnabled(false);
                salaireT.setEnabled(false);
                NumDeptT.setEnabled(false);
                
                
        // Table DEPT
                
                NumDept3.setSelected(false);
                NomDept.setSelected(false);
                Budget.setSelected(false);
                
                NumDept3.setEnabled(false);
                NomDept.setEnabled(false);
                Budget.setEnabled(false);
                
                NumDept4.setSelectedIndex(0);
                Nomdept2.setSelectedIndex(0);
                Budget2.setSelectedIndex(0);
                Budget3.removeAllItems();
                
                cond_agregat1.setEnabled(false);
                NumDept4.setEnabled(false);
                Nomdept2.setEnabled(false);
                Budget2.setEnabled(false);
                Budget3.setEnabled(false);
                
                
                NumDeptT2.setText("");
                NomDeptT.setText("");
                BudgetT.setText("");
                
                NumDeptT2.setEnabled(false);
                NomDeptT.setEnabled(false);
                BudgetT.setEnabled(false);
                
                
        
    }

                 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        rouge1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jaune2 = new javax.swing.JPanel();
        jaune1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        bleu = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        bord1_orange = new javax.swing.JPanel();
        T_Departement = new javax.swing.JCheckBox();
        bord2_orang = new javax.swing.JPanel();
        T_Employe = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        att_tab1_rose = new javax.swing.JPanel();
        NomEmp = new javax.swing.JRadioButton();
        salaire = new javax.swing.JRadioButton();
        NumDept = new javax.swing.JRadioButton();
        NomEmp1 = new javax.swing.JComboBox<>();
        salaire1 = new javax.swing.JComboBox<>();
        NumDept1 = new javax.swing.JComboBox<>();
        salaire2 = new javax.swing.JComboBox<>();
        NomEmpT = new javax.swing.JTextField();
        NumDeptT = new javax.swing.JTextField();
        att_tab2_rose = new javax.swing.JPanel();
        NumDept3 = new javax.swing.JRadioButton();
        NomDept = new javax.swing.JRadioButton();
        Budget = new javax.swing.JRadioButton();
        jPanel7 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        cond_agregat = new javax.swing.JComboBox<>();
        jPanel10 = new javax.swing.JPanel();
        NumDept4 = new javax.swing.JComboBox<>();
        Nomdept2 = new javax.swing.JComboBox<>();
        Budget2 = new javax.swing.JComboBox<>();
        jPanel11 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        Budget3 = new javax.swing.JComboBox<>();
        BudgetT = new javax.swing.JTextField();
        NomDeptT = new javax.swing.JTextField();
        NumDeptT2 = new javax.swing.JTextField();
        cond_agregat1 = new javax.swing.JComboBox<>();
        violet = new javax.swing.JPanel();
        requete_marron = new javax.swing.JPanel();
        r_gauche = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        r_droite = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        la_requete = new javax.swing.JTextArea();
        resultat = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        result = new javax.swing.JTable();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1024, 1024));

        rouge1.setBackground(new java.awt.Color(51, 255, 255));
        rouge1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 5, true));

        javax.swing.GroupLayout rouge1Layout = new javax.swing.GroupLayout(rouge1);
        rouge1.setLayout(rouge1Layout);
        rouge1Layout.setHorizontalGroup(
            rouge1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1335, Short.MAX_VALUE)
        );
        rouge1Layout.setVerticalGroup(
            rouge1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(rouge1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jaune2.setBackground(new java.awt.Color(51, 255, 255));
        jaune2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 5, true));

        javax.swing.GroupLayout jaune2Layout = new javax.swing.GroupLayout(jaune2);
        jaune2.setLayout(jaune2Layout);
        jaune2Layout.setHorizontalGroup(
            jaune2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jaune2Layout.setVerticalGroup(
            jaune2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 714, Short.MAX_VALUE)
        );

        jPanel2.add(jaune2, java.awt.BorderLayout.LINE_START);

        jaune1.setBackground(new java.awt.Color(0, 255, 255));
        jaune1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 5, true));

        javax.swing.GroupLayout jaune1Layout = new javax.swing.GroupLayout(jaune1);
        jaune1.setLayout(jaune1Layout);
        jaune1Layout.setHorizontalGroup(
            jaune1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jaune1Layout.setVerticalGroup(
            jaune1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 714, Short.MAX_VALUE)
        );

        jPanel2.add(jaune1, java.awt.BorderLayout.LINE_END);

        jPanel6.setLayout(new java.awt.BorderLayout());

        bleu.setBackground(new java.awt.Color(51, 255, 255));
        bleu.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 5, true));

        javax.swing.GroupLayout bleuLayout = new javax.swing.GroupLayout(bleu);
        bleu.setLayout(bleuLayout);
        bleuLayout.setHorizontalGroup(
            bleuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1115, Short.MAX_VALUE)
        );
        bleuLayout.setVerticalGroup(
            bleuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel6.add(bleu, java.awt.BorderLayout.PAGE_START);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel8.setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        bord1_orange.setBackground(new java.awt.Color(51, 255, 255));

        T_Departement.setBackground(new java.awt.Color(0, 255, 255));
        T_Departement.setText("Table Département");
        T_Departement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                T_DepartementMouseClicked(evt);
            }
        });
        T_Departement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T_DepartementActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bord1_orangeLayout = new javax.swing.GroupLayout(bord1_orange);
        bord1_orange.setLayout(bord1_orangeLayout);
        bord1_orangeLayout.setHorizontalGroup(
            bord1_orangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bord1_orangeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(T_Departement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bord1_orangeLayout.setVerticalGroup(
            bord1_orangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(T_Departement, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
        );

        jPanel1.add(bord1_orange, java.awt.BorderLayout.LINE_END);

        bord2_orang.setBackground(new java.awt.Color(102, 255, 255));

        T_Employe.setBackground(new java.awt.Color(51, 255, 255));
        T_Employe.setText("Table Employé");
        T_Employe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                T_EmployeMouseClicked(evt);
            }
        });
        T_Employe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T_EmployeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bord2_orangLayout = new javax.swing.GroupLayout(bord2_orang);
        bord2_orang.setLayout(bord2_orangLayout);
        bord2_orangLayout.setHorizontalGroup(
            bord2_orangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bord2_orangLayout.createSequentialGroup()
                .addComponent(T_Employe, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        bord2_orangLayout.setVerticalGroup(
            bord2_orangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(T_Employe, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
        );

        jPanel1.add(bord2_orang, java.awt.BorderLayout.LINE_START);

        jPanel3.setLayout(new java.awt.BorderLayout());

        att_tab1_rose.setBackground(new java.awt.Color(0, 255, 255));

        NomEmp.setBackground(new java.awt.Color(51, 255, 255));
        NomEmp.setText("NomEmp");
        NomEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomEmpActionPerformed(evt);
            }
        });

        salaire.setBackground(new java.awt.Color(51, 255, 255));
        salaire.setText("salaire");
        salaire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salaireActionPerformed(evt);
            }
        });

        NumDept.setBackground(new java.awt.Color(51, 255, 255));
        NumDept.setText("NumDept");
        NumDept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumDeptActionPerformed(evt);
            }
        });

        NomEmp1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none", "=" }));

        salaire1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none", "Agregat", "Operateur" }));
        salaire1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salaire1MouseClicked(evt);
            }
        });
        salaire1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salaire1ActionPerformed(evt);
            }
        });

        NumDept1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none", "=", ">", "<", ">=", "<=" }));
        NumDept1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumDept1ActionPerformed(evt);
            }
        });

        salaire2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salaire2MouseClicked(evt);
            }
        });
        salaire2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salaire2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout att_tab1_roseLayout = new javax.swing.GroupLayout(att_tab1_rose);
        att_tab1_rose.setLayout(att_tab1_roseLayout);
        att_tab1_roseLayout.setHorizontalGroup(
            att_tab1_roseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(att_tab1_roseLayout.createSequentialGroup()
                .addGroup(att_tab1_roseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(salaire, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NomEmp, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                    .addComponent(NumDept, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(att_tab1_roseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(salaire1, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NumDept1, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NomEmp1, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(att_tab1_roseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NomEmpT)
                    .addComponent(NumDeptT, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                    .addComponent(salaire2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        att_tab1_roseLayout.setVerticalGroup(
            att_tab1_roseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(att_tab1_roseLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(att_tab1_roseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomEmp)
                    .addComponent(NomEmp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NomEmpT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(att_tab1_roseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salaire)
                    .addComponent(salaire1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salaire2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(att_tab1_roseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NumDept)
                    .addComponent(NumDept1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NumDeptT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73))
        );

        jPanel3.add(att_tab1_rose, java.awt.BorderLayout.LINE_START);

        att_tab2_rose.setBackground(new java.awt.Color(51, 255, 255));

        NumDept3.setBackground(new java.awt.Color(0, 255, 255));
        NumDept3.setText("NumDept");

        NomDept.setBackground(new java.awt.Color(0, 255, 255));
        NomDept.setText("NomDept");

        Budget.setBackground(new java.awt.Color(0, 255, 255));
        Budget.setText("Budget");
        Budget.setBorder(null);
        Budget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BudgetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout att_tab2_roseLayout = new javax.swing.GroupLayout(att_tab2_rose);
        att_tab2_rose.setLayout(att_tab2_roseLayout);
        att_tab2_roseLayout.setHorizontalGroup(
            att_tab2_roseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NumDept3, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
            .addComponent(NomDept, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(att_tab2_roseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Budget, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        att_tab2_roseLayout.setVerticalGroup(
            att_tab2_roseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(att_tab2_roseLayout.createSequentialGroup()
                .addComponent(NumDept3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NomDept, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Budget, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                .addGap(37, 37, 37))
        );

        jPanel3.add(att_tab2_rose, java.awt.BorderLayout.LINE_END);

        jPanel7.setLayout(new java.awt.BorderLayout());

        jPanel9.setBackground(new java.awt.Color(0, 255, 255));

        cond_agregat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none" }));
        cond_agregat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cond_agregatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cond_agregat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(cond_agregat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        jPanel7.add(jPanel9, java.awt.BorderLayout.LINE_START);

        jPanel10.setBackground(new java.awt.Color(0, 255, 255));

        NumDept4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none", "=", ">", "<", ">=", "<=" }));

        Nomdept2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none", "=" }));

        Budget2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none", "Agregat", "Operateur" }));
        Budget2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Budget2MouseClicked(evt);
            }
        });
        Budget2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Budget2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NumDept4, 0, 65, Short.MAX_VALUE)
                    .addComponent(Nomdept2, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Budget2, 0, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NumDept4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Nomdept2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(Budget2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        jPanel7.add(jPanel10, java.awt.BorderLayout.LINE_END);

        jPanel11.setBackground(new java.awt.Color(51, 255, 255));
        jPanel11.setLayout(new java.awt.BorderLayout());

        jPanel13.setBackground(new java.awt.Color(0, 255, 255));

        Budget3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Budget3MouseClicked(evt);
            }
        });
        Budget3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Budget3ActionPerformed(evt);
            }
        });

        cond_agregat1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none" }));
        cond_agregat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cond_agregat1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(BudgetT, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(cond_agregat1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(NomDeptT)
                    .addComponent(NumDeptT2)
                    .addComponent(Budget3, 0, 68, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NumDeptT2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(NomDeptT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Budget3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cond_agregat1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BudgetT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69))
        );

        jPanel11.add(jPanel13, java.awt.BorderLayout.LINE_END);

        jPanel7.add(jPanel11, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel7, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel8.add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel8, java.awt.BorderLayout.PAGE_START);

        violet.setBackground(new java.awt.Color(102, 0, 102));
        violet.setLayout(new java.awt.BorderLayout());

        requete_marron.setBackground(new java.awt.Color(153, 102, 0));
        requete_marron.setLayout(new java.awt.BorderLayout());

        r_gauche.setBackground(new java.awt.Color(0, 255, 255));

        jButton1.setBackground(new java.awt.Color(204, 0, 0));
        jButton1.setText("La requête est :");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout r_gaucheLayout = new javax.swing.GroupLayout(r_gauche);
        r_gauche.setLayout(r_gaucheLayout);
        r_gaucheLayout.setHorizontalGroup(
            r_gaucheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        r_gaucheLayout.setVerticalGroup(
            r_gaucheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, r_gaucheLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        requete_marron.add(r_gauche, java.awt.BorderLayout.LINE_START);

        r_droite.setBackground(new java.awt.Color(102, 255, 255));

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setText("Executer");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setText("Effacer");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout r_droiteLayout = new javax.swing.GroupLayout(r_droite);
        r_droite.setLayout(r_droiteLayout);
        r_droiteLayout.setHorizontalGroup(
            r_droiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        r_droiteLayout.setVerticalGroup(
            r_droiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(r_droiteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        requete_marron.add(r_droite, java.awt.BorderLayout.LINE_END);

        la_requete.setColumns(20);
        la_requete.setRows(5);
        jScrollPane1.setViewportView(la_requete);

        requete_marron.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        violet.add(requete_marron, java.awt.BorderLayout.PAGE_START);

        resultat.setBackground(new java.awt.Color(0, 153, 204));
        resultat.setLayout(new java.awt.BorderLayout());

        jPanel15.setBackground(new java.awt.Color(51, 255, 255));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1125, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        resultat.add(jPanel15, java.awt.BorderLayout.PAGE_START);

        result.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(result);

        resultat.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        violet.add(resultat, java.awt.BorderLayout.CENTER);

        jPanel5.add(violet, java.awt.BorderLayout.CENTER);

        jPanel6.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel6, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NomEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomEmpActionPerformed

    private void salaireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salaireActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salaireActionPerformed

    private void NumDeptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumDeptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumDeptActionPerformed

    private void T_DepartementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T_DepartementActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T_DepartementActionPerformed

    private void salaire1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salaire1ActionPerformed
        // TODO add your handling code here:
        System.out.println("hello");
         
        if(salaire1.getSelectedItem()=="Agregat"){
            
            salaire2.removeAllItems();
            salaire2.addItem("MAX");
            salaire2.addItem("MIN");
            salaire2.addItem("SUM");
            salaire2.addItem("AVG");
            CodeEmp.setEnabled(false);
            CodeEmp.setSelected(false);
            NomEmp.setEnabled(false);
            NomEmp.setSelected(false);
            
        }if(salaire1.getSelectedItem()=="Operateur"){
            
            salaire2.removeAllItems();
            salaire2.addItem("=");
            salaire2.addItem("<");
            salaire2.addItem(">");
            salaire2.addItem("<=");
            salaire2.addItem(">=");
            CodeEmp.setEnabled(true);
            NomEmp.setEnabled(true);
        }if(salaire1.getSelectedItem()=="none"){
            
            CodeEmp.setEnabled(true);
            NomEmp.setEnabled(true);
        }
        
       
    }//GEN-LAST:event_salaire1ActionPerformed

    private void NumDept1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumDept1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumDept1ActionPerformed

    private void salaire2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salaire2ActionPerformed
        // TODO add your handling code here:
        
        if(salaire2.getSelectedItem()=="SUM"||salaire2.getSelectedItem()=="AVG"){
            cond_agregat.setEnabled(true);
            cond_agregat.removeAllItems();
            cond_agregat.addItem("none");
            cond_agregat.addItem("=");
            cond_agregat.addItem("<");
            cond_agregat.addItem(">");
            cond_agregat.addItem("<=");
            cond_agregat.addItem(">=");
        }else{
            cond_agregat.setEnabled(false);
        }
    }//GEN-LAST:event_salaire2ActionPerformed

    private void T_EmployeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T_EmployeActionPerformed
        // TODO add your handling code here:

        
        
    }//GEN-LAST:event_T_EmployeActionPerformed

    private void T_EmployeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_T_EmployeMouseClicked
        // TODO add your handling code here:
                if(T_Employe.isSelected()){
                //////    
                CodeEmp.setEnabled(true);
                NomEmp.setEnabled(true);
                salaire.setEnabled(true);
                NumDept.setEnabled(true);
                Origine.setEnabled(true);
                //////
                CodeEmp1.setEnabled(true);
                NomEmp1.setEnabled(true);
                NumDept1.setEnabled(true);
                salaire1.setEnabled(true);
                salaire2.setEnabled(true);
                Origine1.setEnabled(true);
                cond_agregat.setEnabled(true);
                ////
                CodeEmpT.setEnabled(true);
                NomEmpT.setEnabled(true);
                salaireT.setEnabled(true);
                NumDeptT.setEnabled(true);
                
                
        }
                if(!T_Employe.isSelected()){
                    
                
                CodeEmp.setSelected(false);
                NomEmp.setSelected(false);
                salaire.setSelected(false);
                NumDept.setSelected(false);
                Origine.setSelected(false);
                    
                CodeEmp.setEnabled(false);
                NomEmp.setEnabled(false);
                salaire.setEnabled(false);
                NumDept.setEnabled(false);
                Origine.setEnabled(false);
                
                CodeEmp1.setSelectedIndex(0);
                NomEmp1.setSelectedIndex(0);
                salaire1.setSelectedIndex(0);
                salaire2.removeAllItems();
                NumDept1.setSelectedIndex(0);
                Origine1.setSelectedIndex(0);
                
                cond_agregat.setEnabled(false);
                CodeEmp1.setEnabled(false);
                NomEmp1.setEnabled(false);
                NumDept1.setEnabled(false);
                salaire1.setEnabled(false);
                salaire2.setEnabled(false);
                Origine1.setEnabled(false);
                
                CodeEmpT.setText("");
                NomEmpT.setText("");
                salaireT.setText("");
                NumDeptT.setText("");
                
                
                CodeEmpT.setEnabled(false);
                NomEmpT.setEnabled(false);
                salaireT.setEnabled(false);
                NumDeptT.setEnabled(false);
                
                }
    }//GEN-LAST:event_T_EmployeMouseClicked

    private void salaire2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salaire2MouseClicked
        // TODO add your handling code here:
        /*
        if(salaire1.getSelectedItem()=="Agregat"){
            
            salaire2.removeAllItems();
            salaire2.addItem("MAX");
            salaire2.addItem("MIN");
            salaire2.addItem("SUM");
            salaire2.addItem("AVG");
            
        }if(salaire1.getSelectedItem()=="Operateur"){
            
            salaire2.removeAllItems();
            salaire2.addItem("=");
            salaire2.addItem("<");
            salaire2.addItem(">");
            salaire2.addItem("<=");
            salaire2.addItem(">=");
        }
        
        */
    }//GEN-LAST:event_salaire2MouseClicked

    private void T_DepartementMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_T_DepartementMouseClicked
        // TODO add your handling code here:
        
        if(T_Departement.isSelected()){
            
                NumDept3.setEnabled(true);
                NomDept.setEnabled(true);
                Budget.setEnabled(true);
                
                
                NumDept4.setEnabled(true);
                Nomdept2.setEnabled(true);
                Budget2.setEnabled(true);
                Budget3.setEnabled(true);
                cond_agregat1.setEnabled(true);
                
                NumDeptT2.setEnabled(true);
                NomDeptT.setEnabled(true);
                BudgetT.setEnabled(true);
                
        }
        
        if(!T_Departement.isSelected()){
            
            
                NumDept3.setSelected(false);
                NomDept.setSelected(false);
                Budget.setSelected(false);
                
                NumDept3.setEnabled(false);
                NomDept.setEnabled(false);
                Budget.setEnabled(false);
                
                NumDept4.setSelectedIndex(0);
                Nomdept2.setSelectedIndex(0);
                Budget2.setSelectedIndex(0);
                Budget3.removeAllItems();
                
                cond_agregat1.setEnabled(false);
                NumDept4.setEnabled(false);
                Nomdept2.setEnabled(false);
                Budget2.setEnabled(false);
                Budget3.setEnabled(false);
                
                NumDeptT2.setText("");
                NomDeptT.setText("");
                BudgetT.setText("");
                
                NumDeptT2.setEnabled(false);
                NomDeptT.setEnabled(false);
                BudgetT.setEnabled(false);
                
        }
        
    }//GEN-LAST:event_T_DepartementMouseClicked

    private void Budget3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Budget3MouseClicked
        // TODO add your handling code here:
        /*
                if(Budget2.getSelectedItem()=="Agregat"){
            
            Budget3.removeAllItems();
            Budget3.addItem("MAX");
            Budget3.addItem("MIN");
            Budget3.addItem("SUM");
            Budget3.addItem("AVG");
            
        }if(Budget2.getSelectedItem()=="Operateur"){
            
            Budget3.removeAllItems();
            Budget3.addItem("=");
            Budget3.addItem("<");
            Budget3.addItem(">");
            Budget3.addItem("<=");
            Budget3.addItem(">=");
        }
        */
    }//GEN-LAST:event_Budget3MouseClicked

    private void Budget2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Budget2ActionPerformed
        // TODO add your handling code here:
        
            if(Budget2.getSelectedItem()=="Agregat"){
            
            Budget3.removeAllItems();
            Budget3.addItem("MAX");
            Budget3.addItem("MIN");
            Budget3.addItem("SUM");
            Budget3.addItem("AVG");
            NomDept.setEnabled(false);
            NomDept.setSelected(false);
            NumDept3.setEnabled(false);
            NumDept3.setSelected(false);
        
            }if(Budget2.getSelectedItem()=="Operateur"){
            
            Budget3.removeAllItems();
            Budget3.addItem("=");
            Budget3.addItem("<");
            Budget3.addItem(">");
            Budget3.addItem("<=");
            Budget3.addItem(">=");
        }

    }//GEN-LAST:event_Budget2ActionPerformed

    private void Budget2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Budget2MouseClicked
        // TODO add your handling code here:
        
        Budget3.removeAllItems();
    }//GEN-LAST:event_Budget2MouseClicked

    private void salaire1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salaire1MouseClicked
        // TODO add your handling code here:
     //   salaire2.removeAllItems();
       //facit 
    }//GEN-LAST:event_salaire1MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        requete="";
    //    if("".equals(select)){
        former_requete();
        la_requete.setText(requete);
    //    }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        if(!"".equals(select)){
        
        former_requete();
        tm=new DefaultTableModel();
        tm = (DefaultTableModel) result.getModel();
        tm.setColumnCount(0);
        tm.setRowCount(0);
        
        try {
            // TODO add your handling code here:

            stmt=maconnexion.obtenirConnexion().createStatement();
            
            r1 = stmt.executeQuery(requete);
                    result.getModel();
                    get_colomn_names();
                    remplir_tableau_resultats();
            stmt.close();
        } catch (SQLException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void cond_agregatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cond_agregatActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cond_agregatActionPerformed

    private void cond_agregat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cond_agregat1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cond_agregat1ActionPerformed

    private void Budget3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Budget3ActionPerformed
        // TODO add your handling code here:
        if(Budget3.getSelectedItem()=="SUM"||Budget3.getSelectedItem()=="AVG"){
          cond_agregat1.setEnabled(true);
            cond_agregat1.removeAllItems();
            cond_agregat1.addItem("none");
            cond_agregat1.addItem("=");
            cond_agregat1.addItem("<");
            cond_agregat1.addItem(">");
            cond_agregat1.addItem("<=");
            cond_agregat1.addItem(">=");
        }else{
            cond_agregat1.setEnabled(false);
        }
    }//GEN-LAST:event_Budget3ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        la_requete.setText("");
        select="";
        where="";
        agregat="";
        groupby="";
        tm.setColumnCount(0);
        tm.setRowCount(0);
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BudgetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BudgetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BudgetActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Budget;
    private javax.swing.JComboBox<String> Budget2;
    private javax.swing.JComboBox<String> Budget3;
    private javax.swing.JTextField BudgetT;
    private javax.swing.JRadioButton NomDept;
    private javax.swing.JTextField NomDeptT;
    private javax.swing.JRadioButton NomEmp;
    private javax.swing.JComboBox<String> NomEmp1;
    private javax.swing.JTextField NomEmpT;
    private javax.swing.JComboBox<String> Nomdept2;
    private javax.swing.JRadioButton NumDept;
    private javax.swing.JComboBox<String> NumDept1;
    private javax.swing.JRadioButton NumDept3;
    private javax.swing.JComboBox<String> NumDept4;
    private javax.swing.JTextField NumDeptT;
    private javax.swing.JTextField NumDeptT2;
    private javax.swing.JCheckBox T_Departement;
    private javax.swing.JCheckBox T_Employe;
    private javax.swing.JPanel att_tab1_rose;
    private javax.swing.JPanel att_tab2_rose;
    private javax.swing.JPanel bleu;
    private javax.swing.JPanel bord1_orange;
    private javax.swing.JPanel bord2_orang;
    private javax.swing.JComboBox<String> cond_agregat;
    private javax.swing.JComboBox<String> cond_agregat1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel jaune1;
    private javax.swing.JPanel jaune2;
    private javax.swing.JTextArea la_requete;
    private javax.swing.JPanel r_droite;
    private javax.swing.JPanel r_gauche;
    private javax.swing.JPanel requete_marron;
    private javax.swing.JTable result;
    private javax.swing.JPanel resultat;
    private javax.swing.JPanel rouge1;
    private javax.swing.JRadioButton salaire;
    private javax.swing.JComboBox<String> salaire1;
    private javax.swing.JComboBox<String> salaire2;
    private javax.swing.JPanel violet;
    // End of variables declaration//GEN-END:variables

    public void former_from() {
     
        from="";
        
        
        if (T_Employe.isSelected() && T_Departement.isSelected()){
            from=from+"Employe e , Departement d";
           
        
        }else {
              if (T_Employe.isSelected()){
                  from=from+"Employe e ";
              }else {
                    if (T_Departement.isSelected()){from=from+" Departement d";}
                     }
               }

    }

    public void former_where() {

        where="";
        
        if (T_Employe.isSelected() && T_Departement.isSelected()){
            where=where+" e.NumDept=d.NumDept ";
        
        }
        
        
        if(T_Employe.isSelected()){
            
            ///codeEmp
            if(CodeEmp.isSelected()){
                if(CodeEmp1.getModel().getSelectedItem()!="none"){
                    if("".equals(where)){
                        where= "e.CodeEmp "+ CodeEmp1.getModel().getSelectedItem() +" " +CodeEmpT.getText() ;
                    }else{
                        where= where +" \n AND e.CodeEmp "+ CodeEmp1.getModel().getSelectedItem() +" " +CodeEmpT.getText() ;
                    }
                    
                }
                
            }
            
            ///NomEmp
            if(NomEmp.isSelected()){
                if(NomEmp1.getModel().getSelectedItem()!="none"){
                    if("".equals(where)){
                        where= "e.NomEmp like '%" +NomEmpT.getText()+"%' " ;
                    }else{
                        where= where +" \n AND e.NomEmp like '% "+NomEmpT.getText() +"%' " ;
                    }
                    
                }
                
            }
            
            ///salaire
            if(salaire.isSelected()){
                if(salaire1.getModel().getSelectedItem()=="Operateur"){
                    if("".equals(where)){
                        where= "e.salaire "+ salaire2.getModel().getSelectedItem() +" " +salaireT.getText() ;
                    }else{
                        where= where +" \n AND e.salaire "+ salaire2.getModel().getSelectedItem() +" " +salaireT.getText() ;
                    }
                    
                }
                
            }
            
            ////NumDept
            if(NumDept.isSelected()){
                if(NumDept1.getModel().getSelectedItem()!="none"){
                    if("".equals(where)){
                        where= "e.NumDept "+ NumDept1.getModel().getSelectedItem() +" " +NumDeptT.getText() ;
                    }else{
                        where= where +" \n AND e.NumDept "+ NumDept1.getModel().getSelectedItem() +" " +NumDeptT.getText() ;
                    }
                    
                }
                
            }
            
            /////Origine
            if(Origine.isSelected()){
                if(Origine1.getModel().getSelectedItem()!="none"){
                    if("".equals(where)){
                        where= "e.Origine = '" +Origine1.getModel().getSelectedItem() +"'";
                    }else{
                        where= where +" \n AND e.Origine = '"+ Origine1.getModel().getSelectedItem()+"'" ;
                    }
                    
                }
                
            }
            
            /////
            
            
        }
        
        ///// Table Departement
        if(T_Departement.isSelected()){
            
            ////NumDept3
            if(NumDept3.isSelected()){
                if(NumDept4.getModel().getSelectedItem()!="none"){
                    if("".equals(where)){
                        where= "d.NumDept "+ NumDept4.getModel().getSelectedItem() +" " +NumDeptT2.getText() ;
                    }else{
                        where= where +" \n AND d.NumDept "+ NumDept4.getModel().getSelectedItem() +" " +NumDeptT2.getText() ;
                    }
                    
                }
                
            }
            
            /////NomDept
            if(NomDept.isSelected()){
                if(Nomdept2.getModel().getSelectedItem()!="none"){
                    if("".equals(where)){
                        where= "d.NomDept like '%"+NomDeptT.getText()+"%' " ;
                    }else{
                        where= where +" \n AND d.NomDept like '%"+NomDeptT.getText()+"%' " ;
                    }
                    
                }
                
            }
            
            
            ////Budget
            if(Budget.isSelected()){
                if(Budget2.getModel().getSelectedItem()=="Operateur"){
                    if("".equals(where)){
                        where= "d.Budget "+ Budget3.getModel().getSelectedItem() +" " +BudgetT.getText() ;
                    }else{
                        where= where +" \n AND d.Budget "+ Budget3.getModel().getSelectedItem() +" " +BudgetT.getText() ;
                    }
                    
                }
                
            }
            
            
            
            
        }
        
    }

    public void former_select() {
     
     agregat="";
     select="";
     cpt=0;
        
        //Table Employe
        if(T_Employe.isSelected()){
            ///codeEmp
            if(CodeEmp.isSelected()){   
                    if("".equals(select)){
                    select = "  e.CodeEmp" ;
                    cpt++;
                    }else{
                        select = select + " , e.CodeEmp";
                        cpt++;
                    }
            }
            ///NomEmp
            if(NomEmp.isSelected()){   
                    if("".equals(select)){
                        select = "  e.NomEmp" ;
                        cpt++;
                    }else{
                        select = select + " , e.NomEmp";
                        cpt++;
                    }    
                }
            
            ///numdept
            if(NumDept.isSelected()){   
                    if("".equals(select)){
                        select = "  e.NumDept" ;
                        cpt++;
                    }else{
                        select = select + " , e.NumDept";
                        cpt++;
                    }    
                }
            
            ///Origine
            if(Origine.isSelected()){   
                    if("".equals(select)){
                       select = "  e.Origine" ;
                       cpt++;
                    }else{
                        select = select + " ,  e.Origine";
                        cpt++;
                    }    
                }
            
            ///salaire
            if(salaire.isSelected()){
                    if(salaire1.getModel().getSelectedItem()!="Agregat"){
                       
                        if("".equals(select)){
                             select = " e.salaire" ;
                             cpt++;
                        }else{
                            select = select + " ,  e.salaire";
                            cpt++;
                        }
                        
                    }
                    
                    
                }
        }
        ////table Departement
        if(T_Departement.isSelected()){
            
            ///NumDept3
            if(NumDept3.isSelected()){   
                    if("".equals(select)){
                         select = "  d.NumDept" ;
                         cpt++;
                    }else{
                        select = select + " ,  d.NumDept";
                        cpt++;
                    }    
                }
            
            ///NomDept
            if(NomDept.isSelected()){   
                    if("".equals(select)){
                         select = "  d.NomDept" ;
                         cpt++;
                    }else{
                        select = select + " ,  d.NomDept";
                        cpt++;
                    }    
                }
            
            ///Budget
            if(Budget.isSelected()){
                
                    if(Budget2.getModel().getSelectedItem()!="Agregat"){
                    
                        if("".equals(select)){
                            select = " d.Budget" ;
                            cpt++;
                        }else{
                            select = select + " ,  d.Budget";
                            cpt++;
                        }
                        
                    }
                    
                    
                }
        }
            
            /////agregation 
            ///salaire
            if(T_Employe.isSelected()){
                if(salaire.isSelected()){
                    if(salaire1.getModel().getSelectedItem()=="Agregat"){
                    
                        groupby=select;
                       
                            if(salaire2.getModel().getSelectedItem()!=null){    
                                if("".equals(select)){
                                        agregat= salaire2.getModel().getSelectedItem() + " ( e.salaire )" ;
                                        select = " "+ agregat;
                                        cpt++;
                                    }else{
                                        agregat= salaire2.getModel().getSelectedItem() + " ( e.salaire )" ;
                                        select = select +" , " + agregat;
                                        cpt++;
                                    }
                            }else{
                                la_requete.setText("erreur : selectionner l' agregation ");
                            }
                        }
                }
            
            }
            ///budget
            if(T_Departement.isSelected()){
               if(Budget.isSelected()){
                
                    if(Budget2.getModel().getSelectedItem()=="Agregat"){

                        groupby=select;

                            if(Budget3.getModel().getSelectedItem()!=null){
                                if("".equals(select)){
                                    agregat= Budget3.getModel().getSelectedItem() + " ( d.Budget )" ;
                                    select = " " + agregat;
                                    cpt++;
                                }else{
                                    agregat= Budget3.getModel().getSelectedItem() + " ( d.Budget )" ;
                                    select = select +" , " + agregat;
                                    cpt++;
                                }
                            }else{
                                la_requete.setText("erreur : selectionner l' agregation ");
                            }    
                        }
               }
            }
        }

    public void former_groupby() {
   
        if((T_Employe.isSelected() || T_Departement.isSelected())&&(!"".equals(groupby))){
            
            if((salaire1.getModel().getSelectedItem()=="Agregat") || (Budget2.getModel().getSelectedItem()=="Agregat")){
                requete = requete + "\n GROUP BY ( " + groupby + " )";
            }
        }
        
    }

    public void get_colomn_names() throws SQLException {

        ResultSetMetaData columns = r1.getMetaData();
        int i = 0;
        columnNames.clear();
        while (i < columns.getColumnCount()) {
          i++;
        
          columnNames.add(columns.getColumnName(i));
        }
    
    }

    public void remplir_tableau_resultats() throws SQLException {
            
        tm=new DefaultTableModel();
        tm = (DefaultTableModel) result.getModel();
        tm.setColumnCount(0);
        tm.setRowCount(0);
        ////ajout des colonnes a la table resultats
        for (int i = 0; i < columnNames.size(); i++) {
            tm.addColumn(columnNames.get(i));
            }
        
        Object[] obj = new Object[] {};
        Vector newObj = new Vector<>();

        while (r1.next()) {
            newObj = new Vector<>();
            for (int i = 1 ; i <= columnNames.size(); i++) {
              
                newObj.add(r1.getObject(i));
            }
          
          tm.addRow(newObj);
          
         }
        }

    public void former_having() {
        
        if(!"".equals(agregat)){
            if(cond_agregat.getSelectedItem()!="none"){
                agregat = agregat+ " "+cond_agregat.getSelectedItem() + " " +salaireT.getText();
            
            requete=requete+ "\n HAVING "+agregat;
            }
        
        }
    }

    public void former_requete() {
    
        la_requete.setText("");
        // construction de la requete : 
        former_select();
        former_from();
        former_where();
        
        if(!"".equals(select)){
           requete=" SELECT "+ select +"\n FROM "+ from; 
           if(!"".equals(where)){
               requete=requete+ "\n WHERE "+ where;
           }
        }
        former_groupby();
        former_having();
        
        
        
        la_requete.setText(requete );//+ "\n cpt = "+cpt);
      //  System.out.println(requete);
    }
    }
    
    
            
     

    

